### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by EQuimper** [cassidoo/vim-up#1]
Hello I get this error when I try `rake` .

```
~/bin/vim -c "PluginInstall!" -c "q" -c "q"
sh: /Users/emanuelquimper/bin/vim: No such file or directory
rake aborted!
Command failed with status (127): [~/bin/vim -c "PluginInstall!" -c "q" -c "q...]
/Users/emanuelquimper/VimSetup/vim-up/Rakefile:149:in `block (2 levels) in <top (required)>'
/Users/emanuelquimper/VimSetup/vim-up/Rakefile:190:in `block in <top (required)>'
Tasks: TOP => install:vundle
(See full trace by running task with --trace)
```

**Comment by EQuimper** [comment]
```
➜  vim-up git:(master) rake --trace
** Invoke default (first_time)
** Invoke install (first_time)
** Execute install
** Invoke install:brew (first_time)
** Execute install:brew

-- Homebrew --------------------------------------------------------------------
** Invoke install:the_silver_searcher (first_time)
** Execute install:the_silver_searcher

-- the_silver_searcher ---------------------------------------------------------
** Invoke install:iterm (first_time)
** Execute install:iterm

-- iterm2 ----------------------------------------------------------------------
** Invoke install:ctags (first_time)
** Execute install:ctags

-- ctags -----------------------------------------------------------------------
** Invoke install:reattach_to_user_namespace (first_time)
** Execute install:reattach_to_user_namespace

-- reattach-to-user-namespace --------------------------------------------------

-- symlink ---------------------------------------------------------------------
** Invoke install:vundle (first_time)
** Execute install:vundle

-- vundle ----------------------------------------------------------------------
~/bin/vim -c "PluginInstall!" -c "q" -c "q"
sh: /Users/emanuelquimper/bin/vim: No such file or directory
rake aborted!
Command failed with status (127): [~/bin/vim -c "PluginInstall!" -c "q" -c "q...]
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/emanuelquimper/VimSetup/vim-up/Rakefile:149:in `block (2 levels) in <top (required)>'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/emanuelquimper/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/emanuelquimper/VimSetup/vim-up/Rakefile:190:in `block in <top (required)>'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/emanuelquimper/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/emanuelquimper/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/emanuelquimper/.rvm/gems/ruby-2.3.3@global/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/emanuelquimper/.rvm/rubies/ruby-2.3.3/bin/rake:22:in `load'
/Users/emanuelquimper/.rvm/rubies/ruby-2.3.3/bin/rake:22:in `<main>'
Tasks: TOP => install:vundle
```

**Comment by cassidoo** [comment]
Hm, try changing this line in your Rakefile:
https://github.com/cassidoo/vim-up/blob/master/Rakefile#L149

To:
`sh '~/usr/bin/vim -c "PluginInstall!" -c "q" -c "q"'`

Does that work?

**Comment by EQuimper** [comment]
No :(

**Comment by ChristopherJones72521** [comment]
Having a similar issue. The path `/Users/Chris/bin` exists, but I tried the `/Users/Chris/usr/bin` path for funsies. Sometimes these things work. Thanks for your help. 

```
~/usr/bin/vim -c "PluginInstall!" -c "q" -c "q"
sh: /Users/Chris/usr/bin/vim: No such file or directory
rake aborted!
Command failed with status (127): [~/usr/bin/vim -c "PluginInstall!" -c "q" -...]
/Users/Chris/Desktop/vim-up-master/Rakefile:149:in `block (2 levels) in <top (required)>'
/Users/Chris/Desktop/vim-up-master/Rakefile:190:in `block in <top (required)>'
/Users/Chris/.rvm/gems/ruby-2.1.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => install:vundle
(See full trace by running task with --trace)
```

**Comment by cassidoo** [comment]
Thanks @ChristopherJones72521!  Something you can try is manually putting the `/.vim` folder and the `.vimrc` files in your home directory, and then manually installing iTerm.  It's not as easy, but it'd get the job done.

@EQuimper, I think what you'll have to do is find out where your `bin` folder is, and then change that line to match its path.  If not, try what I told Christopher above.

**Comment by ChristopherJones72521** [comment]
@cassidoo I've tried ~/bin/vim and ~/Users/Chris/bin/vim (which are both valid paths) and no luck still

```
/Users/Chris/bin/vim -c "PluginInstall!" -c "q" -c "q"                                                                                  │
sh: /Users/Chris/bin/vim: No such file or directory                                                                                     │
rake aborted!                                                                                                                           │
Command failed with status (127): [/Users/Chris/bin/vim -c "PluginInstall!" -...]                                                       │
/Users/Chris/Desktop/vim-up-master/Rakefile:149:in `block (2 levels) in <top (required)>'                                               │
/Users/Chris/Desktop/vim-up-master/Rakefile:190:in `block in <top (required)>'                                                          │
/Users/Chris/.rvm/gems/ruby-2.1.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'                                                    │
Tasks: TOP => install:vundle                                                                                                            │
(See full trace by running task with --trace)
```
